WITH SALE (SHOP, YM, AMT) AS (
    SELECT '동대문', '201401', 12800 FROM DUAL UNION ALL
    SELECT '동대문', '201403', 22700 FROM DUAL UNION ALL
    SELECT '동대문', '201403', 22700 FROM DUAL UNION ALL
    SELECT '동대문', '201404', 32350 FROM DUAL UNION ALL
    SELECT '동대문', '201405', 22000 FROM DUAL UNION ALL
    SELECT 'GS마켓', '201401', 13020 FROM DUAL UNION ALL
    SELECT 'GS마켓', '201404', 14100 FROM DUAL
    ), YM AS (
    SELECT TO_CHAR(ADD_MONTHS(TO_DATE('201401', 'YYYYMM'), LEVEL - 1), 'YYYYMM') AS YM
    FROM DUAL
    CONNECT BY LEVEL <= 06
)
-- 쿼리 작성
SELECT 
    NVL(SHOP_LIST.SHOP, '소계') AS SHOP,
    SHOP_LIST.YM AS YM,
    SUM(NVL(SA.AMT, 0)) AS MM_AMT 
FROM 
    (SELECT DISTINCT A.SHOP, B.YM FROM SALE A, YM B) SHOP_LIST
    LEFT OUTER JOIN SALE SA
        ON SHOP_LIST.SHOP = SA.SHOP AND SHOP_LIST.YM = SA.YM
GROUP BY GROUPING SETS ((SHOP_LIST.SHOP, SHOP_LIST.YM), (SHOP_LIST.YM))
ORDER BY YM, SHOP;
    
-- GOOD;    
SELECT TO_DATE('20140101', 'YYYYMMDD') + (LEVEL-1) AS YYMM, LEVEL AS YM, LEVEL+1
    FROM DUAL
    CONNECT BY LEVEL <= 10;
    
WITH SALE (SHOP, YM, AMT) AS(
  SELECT '동대문', '201401', 12800 FROM DUAL UNION ALL
  SELECT '동대문', '201403', 22700 FROM DUAL UNION ALL
  SELECT '동대문', '201403', 22700 FROM DUAL UNION ALL
  SELECT '동대문', '201404', 32350 FROM DUAL UNION ALL
  SELECT '동대문', '201405', 22000 FROM DUAL UNION ALL
  SELECT 'GS마켓', '201401', 13020 FROM DUAL UNION ALL
  SELECT 'GS마켓', '201404', 14100 FROM DUAL
), YM AS( 
    SELECT TO_CHAR(ADD_MONTHS(TO_DATE('201401', 'YYYYMM'), LEVEL - 1), 'YYYYMM') AS YM
    FROM DUAL
 CONNECT BY LEVEL <= 06
)
SELECT 
    NVL(SHOP_LIST.SHOP, '소계') AS SHOP,
    SHOP_LIST.YM AS YM,
    SUM(NVL(SA.AMT,0)) AS MM_AMT 
FROM 
    (SELECT DISTINCT A.SHOP, B.YM FROM SALE A, YM B) SHOP_LIST
    LEFT OUTER JOIN SALE SA
        ON SHOP_LIST.SHOP = SA.SHOP AND SHOP_LIST.YM = SA.YM
GROUP BY GROUPING SETS ((SHOP_LIST.SHOP, SHOP_LIST.YM), (SHOP_LIST.YM))
ORDER BY YM, SHOP;

-- CONNECT BY LEVEL 응용
SELECT LEVEL, LEVEL*2, LEVEL*100, LEVEL*LEVEL FROM DUAL
CONNECT BY LEVEL <= 10;

-- 2021-01-01 7일 이후 데이터를 출력하는 쿼리
SELECT (TO_DATE('20210101', 'YYYYMMDD') + (LEVEL*7)) AS PRINT_FRIDAY FROM DUAL
CONNECT BY LEVEL <= 12;

-- !TIP : 날짜가 21/01/08 형태로 나오는 이유
-- 오라클의 NLS_DATE_FORMAT이 RR/MM/DD 로 되어 있기 때문 입니다.
-- TO_CHAR로 변경하지 않은 기본 DATE는 NLS_DATE_FORMAT을 따릅니다.
SELECT SYSDATE FROM DUAL;
SELECT * FROM V$NLS_PARAMETERS WHERE PARAMETER = 'NLS_DATE_FORMAT';

SELECT TO_CHAR(ADD_MONTHS(TO_DATE('202101', 'YYYYMM'), LEVEL - 1), 'YYYY-MM-DD') AS MONTH_LIST FROM DUAL
CONNECT BY LEVEL <= 12;

SELECT TO_DATE('20210101', 'YYYYMMDD') FROM DUAL;

