WITH SALE (SHOP, YM, AMT) AS (
    SELECT '동대문', '201401', 12800 FROM DUAL UNION ALL
    SELECT '동대문', '201403', 22700 FROM DUAL UNION ALL
    SELECT '동대문', '201403', 22700 FROM DUAL UNION ALL
    SELECT '동대문', '201404', 32350 FROM DUAL UNION ALL
    SELECT '동대문', '201405', 22000 FROM DUAL UNION ALL
    SELECT 'GS마켓', '201401', 13020 FROM DUAL UNION ALL
    SELECT 'GS마켓', '201404', 14100 FROM DUAL
    ), YM AS (
    SELECT TO_CHAR(ADD_MONTHS(TO_DATE('201401', 'YYYYMM'), LEVEL - 1), 'YYYYMM') AS YM
    FROM DUAL
    CONNECT BY LEVEL <= 06
)
-- 쿼리 작성
SELECT 
    NVL(SHOP_LIST.SHOP, '소계') AS SHOP,
    SHOP_LIST.YM AS YM,
    SUM(NVL(SA.AMT, 0)) AS MM_AMT 
FROM 
    (SELECT DISTINCT A.SHOP, B.YM FROM SALE A, YM B) SHOP_LIST
    LEFT OUTER JOIN SALE SA
        ON SHOP_LIST.SHOP = SA.SHOP AND SHOP_LIST.YM = SA.YM
GROUP BY GROUPING SETS ((SHOP_LIST.SHOP, SHOP_LIST.YM), (SHOP_LIST.YM))
ORDER BY YM, SHOP;
    
-- GOOD;    
SELECT TO_DATE('20140101', 'YYYYMMDD') + (LEVEL-1) AS YYMM, LEVEL AS YM, LEVEL+1
    FROM DUAL
    CONNECT BY LEVEL <= 10;
    
WITH SALE (SHOP, YM, AMT) AS(
  SELECT '동대문', '201401', 12800 FROM DUAL UNION ALL
  SELECT '동대문', '201403', 22700 FROM DUAL UNION ALL
  SELECT '동대문', '201403', 22700 FROM DUAL UNION ALL
  SELECT '동대문', '201404', 32350 FROM DUAL UNION ALL
  SELECT '동대문', '201405', 22000 FROM DUAL UNION ALL
  SELECT 'GS마켓', '201401', 13020 FROM DUAL UNION ALL
  SELECT 'GS마켓', '201404', 14100 FROM DUAL
), YM AS( 
    SELECT TO_CHAR(ADD_MONTHS(TO_DATE('201401', 'YYYYMM'), LEVEL - 1), 'YYYYMM') AS YM
    FROM DUAL
 CONNECT BY LEVEL <= 06
)
SELECT 
    NVL(SHOP_LIST.SHOP, '소계') AS SHOP,
    SHOP_LIST.YM AS YM,
    SUM(NVL(SA.AMT,0)) AS MM_AMT 
FROM 
    (SELECT DISTINCT A.SHOP, B.YM FROM SALE A, YM B) SHOP_LIST
    LEFT OUTER JOIN SALE SA
        ON SHOP_LIST.SHOP = SA.SHOP AND SHOP_LIST.YM = SA.YM
GROUP BY GROUPING SETS ((SHOP_LIST.SHOP, SHOP_LIST.YM), (SHOP_LIST.YM))
ORDER BY YM, SHOP;

-- CONNECT BY LEVEL 응용
SELECT LEVEL, LEVEL*2, LEVEL*100, LEVEL*LEVEL FROM DUAL
CONNECT BY LEVEL <= 10;

SELECT (TO_DATE('20210101', 'YYYYMMDD') + (LEVEL*7)) AS PRINT_FRIDAY FROM DUAL
CONNECT BY LEVEL <= 10;

