/* 204P 그룹함수 */

SELECT DNAME, JOB, COUNT(*) AS "TOTAL EMPL", SUM(SAL) "TOTAL SAL" FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DNAME, JOB

/* INLINE JOIN 확인 */
SELECT * FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

-- 정렬
SELECT DNAME, JOB, COUNT(*) AS "TOTAL EMPL", SUM(SAL) "TOTAL SAL" FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DNAME, JOB
ORDER BY DNAME, JOB;

-- ROLLUP 
SELECT DNAME, JOB, COUNT(*) AS "TOTAL EMPL", SUM(SAL) "TOTAL SAL" FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
GROUP BY ROLLUP(DNAME, JOB);

-- ROLLUP + ORDER BY 
SELECT DNAME, JOB, COUNT(*) AS "TOTAL EMPL", SUM(SAL) "TOTAL SAL" FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
GROUP BY ROLLUP(DNAME, JOB)
ORDER BY DNAME,JOB;

-- GROUPING 함수 (206P)
-- ROLLUP 또는 CUBE에 의해 소계가 계산된 경우에는 GROUPING(EXPR) = 1
SELECT DNAME, GROUPING(DNAME), JOB, GROUPING(JOB), COUNT(*) AS "TOTAL EMPL", SUM(SAL) "TOTAL SAL" FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
GROUP BY ROLLUP(DNAME, JOB);

-- GROUPBING 함수 + CASE 활용
SELECT 
    CASE WHEN GROUPING(DNAME) = 1 THEN 'ALL DEPT'
        ELSE DNAME END AS "DNAME",
    CASE WHEN GROUPING(JOB) = 1 THEN 'ALL JOB'
        ELSE JOB END AS "JOB",
        COUNT(*) AS "TOTAL EMPL",
        SUM(SAL) "TOTAL SAL" 
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
GROUP BY ROLLUP(DNAME, JOB);
        
-- ROLLUP 함수 일부사용 (전체합계 X)
SELECT DNAME, GROUPING(DNAME), JOB, GROUPING(JOB), COUNT(*) AS "TOTAL EMPL", SUM(SAL) "TOTAL SAL" FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DNAME, ROLLUP(JOB);

-- ROLLUP 함수 결합 컬럼 사용
SELECT DNAME, JOB, MGRCOUNT(*) AS "TOTAL EMPL", SUM(SAL) "TOTAL SAL" FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
GROUP BY ROLLUP(DNAME, (JOB, MGR));

SELECT DNAME, JOB, MGR, COUNT(*) AS "TOTAL EMPL", SUM(SAL) "TOTAL SAL" FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DNAME, JOB, MGR;

-- CUBE 함수 (207P~)
-- DNAME 과 JOB의 모든 조합을 보여줌
SELECT 
    CASE WHEN GROUPING(DNAME) = 1 THEN 'ALL DEPT'
        ELSE DNAME END AS "DNAME",
    CASE WHEN GROUPING(JOB) = 1 THEN 'ALL JOB'
        ELSE JOB END AS "JOB",
        COUNT(*) AS "TOTAL EMPL",
        SUM(SAL) "TOTAL SAL" 
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
GROUP BY CUBE(DNAME, JOB);

-- UNION ALL 사용 SQL
SELECT DNAME, JOB, COUNT(*) "TOTAL EMPL", SUM(SAL) "TOTAL SAL" FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO GROUP BY DNAME, JOB
UNION ALL
SELECT DNAME, 'ALL JOBS', COUNT(*) "TOTAL EMPL", SUM(SAL) "TOTAL SAL" FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO GROUP BY DNAME
UNION ALL
SELECT 'ALL DEPT', JOB, COUNT(*) "TOTAL EMPL", SUM(SAL) "TOTAL SAL" FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO GROUP BY JOB
UNION ALL
SELECT 'ALL DEPT', 'ALL JOBS', COUNT(*) "TOTAL EMPL", SUM(SAL) "TOTAL SAL" FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

/* GROUPING SETS 함수 208P~ */
-- 일반 그룹함수를 이용한 SQL
-- 일반 그룹함수를 이용하여 부서별, JOB별 인원수와 급여 합 구하기
SELECT DNAME, 'ALL JOBS', COUNT(*) "TOTAL EMPL", SUM(SAL) "TOTAL SAL" FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO GROUP BY DNAME
UNION ALL
SELECT 'ALL DEPT', JOB, COUNT(*) "TOTAL EMPL", SUM(SAL) "TOTAL SAL" FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO GROUP BY JOB;

-- GROUPING SETS 함수 사용
SELECT 
    DECODE(GROUPING(DNAME), 1, 'ALL DEPT', DNAME) AS DNAME,
    DECODE(GROUPING(JOB), 1, 'ALL JOBS', JOB) AS JOB,
    COUNT(*) "TOTAL EMPL",
    SUM(SAL) "TOTAL SAL"
FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO
    GROUP BY GROUPING SETS (DNAME, JOB);
    
SELECT 
    DECODE(GROUPING(DNAME), 1, 'ALL DEPT', DNAME) AS DNAME,
    DECODE(GROUPING(JOB), 1, 'ALL JOBS', JOB) AS JOB,
    COUNT(*) "TOTAL EMPL",
    SUM(SAL) "TOTAL SAL"
FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO
    GROUP BY DNAME, JOB;

SELECT 
    DECODE(GROUPING(DNAME), 1, 'ALL DEPT', DNAME) AS DNAME,
    DECODE(GROUPING(JOB), 1, 'ALL JOBS', JOB) AS JOB,
    COUNT(*) "TOTAL EMPL",
    SUM(SAL) "TOTAL SAL"
FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO
    GROUP BY GROUPING SETS (JOB, DNAME);
    
-- 3개의 인수를 이용한 GROUPING SETS 이용
SELECT 
    DNAME, JOB, MGR,
    COUNT(*) "TOTAL EMPL",
    SUM(SAL) "TOTAL SAL"
FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO
    GROUP BY GROUPING SETS ((DNAME, JOB, MGR), (DNAME, JOB), (JOB, MGR));


