/* 143P 숫자형 함수 테스트 */
SELECT HEIGHT, SIGN(HEIGHT-180) FROM PLAYER;

/* 144P 날짜형 함수 */
-- SYSDATE, SYSTIMESTAMP
-- EXTRACT
-- 숫자형 함수 ROUND, TRUNC 
SELECT SYSDATE, 
    EXTRACT(YEAR FROM SYSDATE) 년도,
    EXTRACT(MONTH FROM SYSDATE) 월,
    EXTRACT(DAY FROM SYSDATE) 일,
    SYSTIMESTAMP - INTERVAL '1' minute,
    EXTRACT(YEAR FROM SYSTIMESTAMP) 년도2,
    EXTRACT(MONTH FROM SYSTIMESTAMP) 월2,
    EXTRACT(DAY FROM SYSTIMESTAMP) 일2,
    EXTRACT(MINUTE FROM SYSTIMESTAMP) 분,
    EXTRACT(SECOND FROM SYSTIMESTAMP) 초,
    ROUND(EXTRACT(SECOND FROM SYSTIMESTAMP), 0) 초2,    
    TRUNC(EXTRACT(SECOND FROM SYSTIMESTAMP), 0) 초3    
    FROM DUAL;

SELECT EXTRACT(MONTH FROM HIREDATE) 입사월,
    EXTRACT(DAY FROM HIREDATE) 입사일
    FROM EMP;

SELECT ENAME,
    HIREDATE,
    TO_NUMBER(TO_CHAR(HIREDATE, 'YYYY')) 입사년도,
    TO_NUMBER(TO_CHAR(HIREDATE, 'MM')) 입사월,
    TO_NUMBER(TO_CHAR(HIREDATE, 'DD')) 입사일,
    SYSTIMESTAMP,
    TO_NUMBER(TO_CHAR(SYSTIMESTAMP, 'hh24')) 시간,
    TO_NUMBER(TO_CHAR(SYSTIMESTAMP, 'mi')) 분,
    TO_NUMBER(TO_CHAR(SYSTIMESTAMP, 'ss')) 초, -- 1초인 경우 1
    TO_CHAR(SYSTIMESTAMP, 'ss') 초2, -- 1초인경우 01로
    TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD hh24:mi:SS') TS
FROM EMP;
    