/* 132P~ 비교연산자 */

SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키 FROM PLAYER
WHERE TEAM_ID = 'K01';

SELECT PLAYER_NAME 선수이름, TEAM_ID, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키 FROM PLAYER
WHERE TEAM_ID IN ('K01', 'K02');

-- 다중리스트 (134PAGE)
SELECT PLAYER_NAME 선수이름, TEAM_ID, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키 FROM PLAYER
WHERE (TEAM_ID, POSITION) IN (('K01', 'MF'),('K02', 'MF'))
ORDER BY TEAM_ID, 키 DESC;

-- 논리연산자 (136PAGE)
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키 FROM PLAYER
WHERE TEAM_ID IN ('K02','K07') AND POSITION = 'MF'
ORDER BY 키;

-- 논리연산자 (137PAGE)
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키 FROM PLAYER
WHERE (TEAM_ID = 'K02' OR TEAM_ID = 'K07') AND POSITION = 'MF' AND HEIGHT >= 170 AND HEIGHT <=180;

SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키 FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K07') AND POSITION = 'MF' AND HEIGHT BETWEEN 170 AND 180;

-- ROWNUM (LIMIT OR PK 생성 용도, 138PAGE)
SELECT ROWNUM 순번, PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키 FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K07') AND POSITION = 'MF' AND HEIGHT BETWEEN 170 AND 180;

-- A CASE (정렬전에 SELECT 하면서 ROWNUM을 부여한다)
SELECT ROWNUM 순번, PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키 FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K07') AND POSITION = 'MF' AND HEIGHT BETWEEN 170 AND 180
ORDER BY 키;

-- B CASE 
SELECT ROWNUM, MF.* FROM 
(SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키 FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K07') AND POSITION = 'MF' AND HEIGHT BETWEEN 170 AND 180 ORDER BY 키) MF;

-- CTAS A (ORA-00998: must name this expression with a column alias <- 오류 주의)
CREATE TABLE MF_CTAS_A AS
SELECT ROWNUM 순번, PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키 FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K07') AND POSITION = 'MF' AND HEIGHT BETWEEN 170 AND 180
ORDER BY 키;
-- CTAS B
CREATE TABLE MF_CTAS_B AS
SELECT ROWNUM 순번, MF.* FROM 
(SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키 FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K07') AND POSITION = 'MF' AND HEIGHT BETWEEN 170 AND 180 ORDER BY 키) MF;

SELECT * FROM MF_CTAS_A;
SELECT * FROM MF_CTAS_B;

-- 문자형 함수 142 PAGE
SELECT LENGTH('SQL    EXPERT') FROM DUAL;
-- DUAL : 사용자 SYS가 소유하며 모든 사용자가 액세스 가능한 테이블이다.
-- SELECT ~ FROM ~ 의 형식을 갖추기 위한 일종의 DUMMY 테이블이다.
SELECT * FROM DUAL;
-- DUMMY라는 컬럼에 'X'라는 값이 들어있는 행을 1건 포함하고 있다.
DESCRIBE DUAL;

SELECT CONCAT(PLAYER_NAME, '축구선수') 선수명 FROM PLAYER;
SELECT PLAYER_NAME||'축구선수' 선수명 FROM PLAYER;

SELECT STADIUM_ID, DDD||TEL TEL, LENGTH(DDD||TEL) T_LEN FROM STADIUM
ORDER BY T_LEN;

-- 날짜형 함수 144PAGE

SELECT ENAME, HIREDATE, TO_NUMBER(TO_CHAR(HIREDATE, 'MM')) 입사월 FROM EMP;
SELECT ENAME, HIREDATE, TO_CHAR(HIREDATE, 'MM') 입사월 FROM EMP;