-- BYTE, CHARACTER SEMANTICS 확인용 테이블 생성 
-- 테이블 명 : CHECK_LEN
CREATE TABLE CHECK_LEN (
    CHK_VARCHAR VARCHAR2(10), -- VARCHAR (N)
    CHK_VAR_BYTE VARCHAR2(10 BYTE), -- VARCHAR (N BYTE)
    CHK_VAR_CHAR VARCHAR2(10 CHAR) -- VARCHAR (N CHAR)
);

-- 생성한 테이블의 컬럼정보 확인
-- USER_TAB_COLUMNS 에서 'CHECK_LEN' 테이블 확인
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH 
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'CHECK_LEN';
    
-- 한글 3글자 INSERT 테스트
-- 한글 1글자 3BYTES, 3 BYTES * 3 = 9BYTES로 정상적으로 INSERT
INSERT INTO CHECK_LEN VALUES ('홍길동', '홍길동', '홍길동');

SELECT LENGTHB(CHK_VARCHAR), LENGTHB(CHK_VAR_BYTE), LENGTHB(CHK_VAR_CHAR) FROM CHECK_LEN;

-- VARCHAR2 (CHAR 10) 에는 '홍길동입니다' INSERT 성공
INSERT INTO CHECK_LEN(CHK_VAR_CHAR) VALUES ('홍길동입니다');

-- VARCHAR2 (BYTE 10) 에는 '홍길동입니다' INSERT 실패 
-- 한글 6글자는 18BYTES 
INSERT INTO CHECK_LEN (CHK_VAR_BYTE) VALUES ('홍길동입니다');

-- 확인
-- LENGHTB : 문자열의 길이를 BYTES 로 변환해주는 오라클 내장 함수
SELECT LENGTHB(CHK_VARCHAR), LENGTHB(CHK_VAR_BYTE), LENGTHB(CHK_VAR_CHAR) FROM CHECK_LEN;

-- 확인
-- LENGHT : 문자의 개수를 반환해주는 오라클 내장 함수
SELECT LENGTH(CHK_VARCHAR), LENGTH(CHK_VAR_BYTE), LENGTH(CHK_VAR_CHAR) FROM CHECK_LEN;    

-- 문자수(CHAR) 기준으로 VARCHAR2 생성시 길이는
-- NLS_DATABASE_PARAMETERS 의 NLS_CHARACTERSET 값을 따름
SELECT * FROM NLS_DATABASE_PARAMETERS
    WHERE PARAMETER = 'NLS_CHARACTERSET';
    
-- VARCHAR2(N) 형식으로 BYTE, CHAR를 명시하지 않을 경우
-- NLS_SESSION_PARAMETERS 의 NSL_LENGTH_SEMANTICS 값을 따른다.
SELECT * FROM NLS_SESSION_PARAMETERS
    WHERE PARAMETER = 'NLS_LENGTH_SEMANTICS';